name: macOS Build

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'  # Specify the Xcode version here

    - name: Build Xcode Project without signing
      run: |
        xcodebuild -scheme goggles -project goggles.xcodeproj -sdk macosx -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CONFIGURATION_BUILD_DIR=./build -skipUnavailableActions true

    - name: Archive App
      run: |
        mkdir -p output
        cp -R ./build/goggles.app output/goggles.app

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: output/


    # - name: Build Xcode Project
    #   run: |
    #     xcodebuild -scheme goggles -project goggles.xcodeproj -sdk macosx -configuration Release clean build
        # Replace 'YourSchemeName' and 'YourWorkspaceName' with your actual scheme and workspace names.
        # Use -project if you have a .xcodeproj file instead of a .xcworkspace.
