name: macOS Build

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Xcode version
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.3'  # Specify the Xcode version here

    - name: Create build directory
      run: mkdir -p ./build

    - name: Set attribute on build directory
      run: xattr -w com.apple.xapple.xcode.CreatedByBuildSystem true ./build

    - name: Build Xcode Project without signing
      run: |
        xcodebuild -scheme goggles -project goggles.xcodeproj -sdk macosx -configuration Release clean build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CONFIGURATION_BUILD_DIR=./build -skipUnavailableActions

    - name: Archive App
      run: |
        mkdir -p output
        cp -R ./build/goggles.app output/goggles.app

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: output/
